# Generated by Django 4.2.4 on 2023-08-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('requestDate', models.DateField()),
                ('requestMethod', models.CharField(max_length=100)),
                ('requestConsult', models.CharField(max_length=1000)),
                ('requestDataReturn', models.CharField(max_length=10000)),
            ],
        ),
    ]
