# Generated by Django 4.2.4 on 2023-08-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='Peticion',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='requestConsult',
            new_name='PeticionConsult',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='requestDataReturn',
            new_name='PeticionDataReturn',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='requestDate',
            new_name='PeticionDate',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='requestId',
            new_name='PeticionId',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='requestMethod',
            new_name='PeticionMethod',
        ),
    ]
